# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aec1f9e21f3eb724602e89196e5f2d82ea2e24816b1c1fea7dcdc63573dde331a99ebdad46fac24823638851f6cc02c0b84b52f6418d71a7a55dfdb5836f593b

test:
  secret_key_base: 51dd30536b985a67012c78267d6cea53f0efcf1ef05a3f312e3f7c750218766cf557691205922046f72448387733ced24800d9600167be804cd6f3ac1709e486

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
